# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: beefcake_go_rpcgen 0.0.1 ruby lib

Gem::Specification.new do |s|
  s.name = "beefcake_go_rpcgen"
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Brad Heller"]
  s.date = "2014-09-11"
  s.description = "An implementation of the Go RPCGen protocol"
  s.email = "brad@cloudability.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".gitignore",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "beefcake_go_rpcgen.gemspec",
    "lib/beefcake/client_backends/go_rpcgen_backend.rb",
    "lib/beefcake_go_rpcgen.rb",
    "lib/wire/.gitkeep",
    "lib/wire/wire.pb.rb",
    "lib/wire/wire.proto",
    "spec/beefcake_go_rpcgen_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/bradhe/beefcake_go_rpcgen"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.2.2"
  s.summary = "Go RPCGen backend for Beefcake"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<beefcake>, [">= 0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.8.0"])
      s.add_development_dependency(%q<yard>, ["~> 0.7"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.4"])
    else
      s.add_dependency(%q<beefcake>, [">= 0"])
      s.add_dependency(%q<rspec>, ["~> 2.8.0"])
      s.add_dependency(%q<yard>, ["~> 0.7"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
    end
  else
    s.add_dependency(%q<beefcake>, [">= 0"])
    s.add_dependency(%q<rspec>, ["~> 2.8.0"])
    s.add_dependency(%q<yard>, ["~> 0.7"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
  end
end

